### ISSUE TITLE
SVG versions of institute logos

### ISSUE THREAD

**Issue by torbjoernk** [JLESC/jlesc.org#1]
We need SVG versions of the institutes' logos. In case SVG is not available, it should at least be high resolution PNG.

- [x] Argonne
- [x] Barcelona
- [x] Illinois
- [x] INRIA
- [x] JSC
- [x] RIKEN

**Comment by pancetta** [comment]
This is what I have/found:
JSC: 
https://upload.wikimedia.org/wikipedia/de/8/8b/J%C3%BClich_fz_logo.svg
BSC: 
http://www.bsc.es/media/1517.svg
NCSA:
http://gladiator.ncsa.uiuc.edu/Images/logo/ncsa_logo_vertical.zip
http://gladiator.ncsa.uiuc.edu/Images/logo/ncsa_logo_horizontal.zip

**Comment by pancetta** [comment]
We have to make sure that SVG files are not accessible from the website. In particular INRIA, RIKEN and ANL do not want to see these files publicly available. I propose to use only jpg or png files, which one can find somewhere else anyway.

**Comment by pancetta** [comment]
Also, we need to use the main JLESC "logo" from the current website: http://publish.illinois.edu/jointlab-esc/. And yes, there is no SVG version of this thing.
